### ISSUE TITLE
Provide AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [KeitIG/museeks#335] opened 2017-04-02 20:05 UTC
Would you be interested in providing an [AppImage](http://appimage.org/) for Linux? It would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.
I'm happy to help if there is interest.

**Comment by YurySolovyov** [comment] 2017-04-02 20:09
Hey, thanks for your interest.
1. Any examples of electron-based apps providing AppImage? It would be cool to have tooling that is easy to integrate without too much effort.
2. Does this has any relation with snap or flatpack? I've seen people requesting these too.

**Comment by probonopd** [comment] 2017-04-02 20:29
Yes, lots of the existing AppImages are Electron apps. 

[electron-builder](https://www.npmjs.com/package/electron-builder) uses it as the default format for Linux. There is also https://www.npmjs.com/package/grunt-appimage but I haven't tried it so far.

You can always make an AppImage by hand by using [appimagetool](https://github.com/probonopd/AppImageKit).

**Comment by KeitIG** [comment] 2017-04-02 21:10
Is it a duplicate of #100?

**Comment by KeitIG** [comment] 2017-04-02 21:12
I'll try to work on electron-builder this week. We have a fresh release so I'm feeling free to work on it

**Comment by probonopd** [comment] 2017-04-03 05:13
> Is it a duplicate of #100?

Well, technically no, since AppImage isn't an "installer", but yes, it serves a similar purpose.

**Comment by KeitIG** [comment] 2017-05-22 13:39
AppImage seems better for app of this kind than snap or flatpak. It will be included in the binaries of the next releases once #339 will be merged.

Thanks again for the suggestion @probonopd.

**Comment by YurySolovyov** [comment] 2017-05-22 13:41
Maybe off-topic, but I kinda wonder if snaps are auto updated or one need to manually install new versions?

**Comment by KeitIG** [comment] 2017-05-22 13:44
I didn't really investigate auto-updating for now. I could not answer this.

**Closed** 2017-06-23 06:29 UTC
Labels: binaries, discussion, enhancement

**Comment by probonopd** [comment] 2017-09-08 19:49
Ping, is there any chance we might see an AppImage on https://github.com/KeitIG/museeks/releases anytime soon? Thanks.

**Comment by YurySolovyov** [comment] 2017-09-08 19:55
I think it will be available as the next release. You can also try building it yourself following instructions on readme.

**Comment by KeitIG** [comment] 2017-09-08 23:28
@probonopd I could update one for the last release if you want to. But yeah, it was planned for the next release.

**Comment by probonopd** [comment] 2017-09-09 08:06
That would be great @KeitIG, thanks.

**Comment by KeitIG** [comment] 2017-09-09 13:59
@probonopd You will find .debs and AppImages of the current master branch there: https://drive.google.com/drive/folders/0Bya5ObHuu9mNS29LMEhoNTJfOWs?usp=sharing

**Comment by probonopd** [comment] 2017-09-09 15:37
@KeitIG works for me locally :+1:  but for a real review I'd need a GitHub Releases download link.

**Comment by KeitIG** [comment] 2017-09-09 22:19
> but for a real review I'd need a GitHub Releases download link.

How that? I am not sure to understand.

The work on installers and AppImage has been between the last release and now. There is still one feature that I would like to implement before the next release, which is the #62, there won't be any re-release of the past version with installers I am afraid.

**Comment by probonopd** [comment] 2017-09-10 04:42
No problem, I'll wait until the next release.

**Comment by probonopd** [comment] 2018-02-09 22:20
Is there an ETA for the next release?
