### ISSUE TITLE
ID3 Tag edition

### ISSUE THREAD

**Issue by cfollet** [KeitIG/museeks#197] opened 2016-09-05 11:06 UTC
It would be nice to be able to edit ID3 tag inside the application. Do you think it's a good idea?

**Comment by KeitIG** [comment] 2016-09-05 11:12
Hello,

thank for your interest, it's a duplicate of https://github.com/KeitIG/museeks/issues/101 :)

**Closed by KeitIG** 2016-09-05 11:12 UTC
