### ISSUE TITLE
Music progess bar freezes on context menu

### ISSUE THREAD

**Issue by cfollet** [KeitIG/museeks#225] opened 2016-09-22 18:43 UTC
While playing a song, the progress freezes if we do a right clic on a song.
![issue](https://cloud.githubusercontent.com/assets/5993096/19626938/b58f0b1a-993c-11e6-9041-6b95b13b9cad.gif)

**Comment by KeitIG** [comment] 2016-09-23 07:35
I could not reproduce this bug. Can you provide me the following informations please ?

- OS
- Museeks version
- Console logs (Settings -> Advanced -> Dev mode)

**Comment by cfollet** [comment] 2016-09-27 19:44
- OS X 10.11.4
- Musseks 0.7.0
- Nothing in logs

**Comment by KeitIG** [comment] 2016-09-28 07:46
Does it do that with all your music files ? Can you send me the files that can help me reproduce it ?

**Comment by cfollet** [comment] 2016-09-28 17:20
It does with all my music files. I think the log has nothing to to with the issue. 
[Gentle Roll.mp3.zip](https://github.com/KeitIG/museeks/files/498824/Gentle.Roll.mp3.zip)

**Comment by KeitIG** [comment] 2016-11-02 16:32
ooooh, I see what's going there. But this should not happen anymore as the context menu is handled by the main process and does no block the render process.

Before I was using `electron.contextMenu` on the renderer process until I encoutered that issue, but it's strange it's still occuring on mac.

**Comment by KeitIG** [comment] 2016-11-02 16:47
![contextmenu](https://cloud.githubusercontent.com/assets/1311607/19938199/614e6498-a124-11e6-8276-c580e1b5e443.gif)

**Comment by cfollet** [comment] 2016-11-08 14:26
So why is this happening anymore?

**Comment by KeitIG** [comment] 2016-11-21 15:08
@cfollet Let's see if it still happens before the next release with an up-to-date version of Electron

**Comment by KeitIG** [comment] 2018-01-19 14:50
This should be fixed in the next release, I added the async option to context menus in the macOS integration branch.

**Closed by KeitIG** 2018-01-19 14:50 UTC
Labels: bug, need-confirmation
