### ISSUE TITLE
Global Shortcuts on Windows

### ISSUE THREAD

**Issue by Nino9614** [KeitIG/museeks#365] opened 2017-10-21 12:13 UTC
Hey Guys,

have u ever considered to add global shortcuts to the app?
Right now you can change to the next/previous track using the "options/tray menu", but how about a global shortcut that would allow the same functionality without opening the tray menu?
I think that this feature would be very useful for a music app.

**Comment by KeitIG** [comment] 2017-10-21 13:38
We support media shortcuts already, I do not see why we should add more global shortcuts. They are not really common and can conflict with other apps.

Maybe I am wrong though.

**Comment by Nino9614** [comment] 2017-10-21 15:28
> We support media shortcuts already, I do not see why we should add more global shortcuts.

Can you show me the current shortcuts? Because i cant find them inside the application and also not on the website. Are those ones global shortcuts or do they only work when you are inside the application?.

>They are not really common and can conflict with other apps.
You could provide a option to turn the global shortcuts off in case u have some conflicts with other applications running along side. In my opinon this is a real deal breaker if you need to jump back into the app (or click using the tray) just to change the song.

**Comment by vprigent** [comment] 2017-12-06 02:32
There seems to be an issue on Ubuntu and probably some other linux distributions about global shortcuts.

On my computer it works once and then I am unable to use them again.

I will try to investigate the issue and edit this post.

**Comment by vprigent** [comment] 2017-12-06 11:50
As it turn out, this seems to be related to how dbus handles such shortcuts with the applications.
https://github.com/electron/electron/issues/3941
The issue is known but no elegant solution has been found yet;

Google play music's team built a fix [there](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/85b0eb57447b99d5d4d1cf443e5bba1f86b3912d)

**Comment by KeitIG** [comment] 2017-12-06 11:56
@Nino9614 Can you confirm that you are/were using Museeks with Ubuntu?

**Comment by Nino9614** [comment] 2017-12-08 12:34
@KeitIG no im using Windows 10 on a 64 Bit System.

**Comment by KeitIG** [comment] 2018-04-02 21:53
@Nino9614 

Here I am again, sorry for the delay. By global shortcuts, I mean if you have media controls on your laptop/keyboard, they _should_ be working fine

example:

![](https://cloud.addictivetips.com/wp-content/uploads/2017/10/media-keys-keyboard.jpg)

I will not integrate global shortcuts like `ctrl-maj-alt-P` for play/pause for example, because this is bad UX and can conflict with other apps.

Closing this for now, feel free to continue discuss it and I will re-open it if there is an actual bug :)

**Closed by KeitIG** 2018-04-02 21:53 UTC
